### PR TITLE
Use pkg-dir instead of app-root-path

### LINKED ISSUE #91: "TypeError: Cannot read properties of undefined (reading 'filename')" when globally installed on Ubuntu
Hi, `spellchecker-cli` v5 doesn't work anymore on a `library/node:lts-alpine` container:

```Shell
/ # npm install -g spellchecker-cli
/ # spellchecker --help
/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/resolve.js:111
		appRootPath = path.dirname(requireFunction.main.filename);
		                                                ^

TypeError: Cannot read properties of undefined (reading 'filename')
    at resolve (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/resolve.js:111:51)
    at module.exports (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/app-root-path.js:6:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
```

### PR DESCRIPTION
**Pull request by tbroadley**
Closes #91.

### CODE REVIEW

File: lib/config/file.ts [hunk 1]
```diff
@@ -36,13 +36,15 @@ export const readConfigFile = (
...
+
   const filePath = [
-    '/.spellcheckerrc.yaml',
-    '/.spellcheckerrc.yml',
-    './spellcheckerrc.json',
-    './spellcheckerrc.jsonc',
+    './.spellcheckerrc.yaml',
+    './.spellcheckerrc.yml',
+    './.spellcheckerrc.json',
+    './.spellcheckerrc.jsonc',
```
Comment (tbroadley) [inline lib/config/file.ts:45]: Whoops, these were not the filenames mentioned in the README. This is a bugfix IMO.

File: test/cli-test.ts [hunk 2]
```diff
@@ -638,6 +627,20 @@ parallel(
 );
 
 describe('Spellchecker CLI (not parallel)', () => {
+  it('exits with an error when no arguments are provided', async () => {
+    // Remove .spellcheckerrc.yml so that Spellchecker CLI doesn't use it in this test.
+    const config = readFileSync('.spellcheckerrc.yml', { encoding: 'utf8' });
+    rmSync('.spellcheckerrc.yml');
```
Comment (tbroadley) [inline test/cli-test.ts:633]: This test fails without these lines, proving that Spellchecker CLI is still reading from `.spellcheckerrc.yml`.
